### ISSUE TITLE
How to add a generic ip camera?

### ISSUE THREAD

**Issue by Ezyweb-uk** [maikito26/plugin.video.surveillanceroom#10]
I'm hoping to add a Reolink IP camera using the rtsp protocol. In the OSMC Surveillance Room addon  settings section for the cameras the host, user, and password are all grayed out. The readme mentions overwriting the url manually to support non-Foscam cameras, which file do I need to edit please? Is it /resources/settings.xml? (I couldn't see port 554 listed).

**Comment by maikito26** [comment]
Probably better to use the Generic IP Camera type in the settings and fill out the full RTSP link including port and user/password.

**Comment by Ezyweb-uk** [comment]
I've set the type for camera 1 to 'Generic IP Camera' but the host setting is grayed out and I can't see how to edit it to enter the RTSP link.

**Comment by maikito26** [comment]
In the Generic IP Camera type, those grayed out fields no longer are used.  Instead, you include the parameters into the URL for the RTSP link.

Here's the snapshot URL example:
https://reolink.com/faq/get-url-of-jpeg-image-captured-reolink-camera/ 

The RTSP url documentation is a bit weaker to find quickly.  There's some indications here:
https://reolink.com/faq/set-up-reolink-camera-in-geovision-vms/

You might need to pass the username & password in the URL... Typically this is done rtsp://username:password@Ipaddress:port/h264Preview_01_main

Play with it and let me know how it goes!

**Comment by Ezyweb-uk** [comment]
Thank you for responding so quickly with the info above. I did have the video RTSP link but couldn't see the url field because I need to scroll down. Once entered I did get a response in OSMC/KODI/SurveillanceRoom on my Raspberry Pi3 but the picture was a continous stream of pixels (same in SurveillanceCameras app).

I then tried SR on an Android TV box and it worked fine. So clearly something wrong with my RPi3/OSMC/KODI setup preventing the video to render correctly (maybe it's FFMPEG).

**Comment by maikito26** [comment]
Cool... yea.  We're passing the RTSP feed directly to the Kodi Player so its rendering is out of our control.  In this case it might be worth checking the Kodi forums to see if anyone has figured this out already. If not, start up a thread there :)
