### ISSUE TITLE
Please add some doc for camera setup

### ISSUE THREAD

**Issue by brunetton** [maikito26/plugin.video.surveillanceroom#2]
Hi, 

I wanted to configure a generic camera, but I miss some doc (in readme.md) : is the video stream url is relative or absolute ? I mean, when given host and port, what to put onto"Video stream URL" ?
- "http://xxx.xxx.x.x:80/video/mjpeg.cgi" ?
- "/video/mjpeg.cgi" ?

Thanks

**Comment by maikito26** [comment]
It would be absolute.  So it would be:

 

http://username:password@ipaddress:port/video/mjpeg.cgi

**Comment by brunetton** [comment]
Thanks !
It's what I guessed. The more probable.

I can add it to readme and make a pull request if you want.

**Comment by maikito26** [comment]
I would be fine with that :)
